### ISSUE TITLE
Not Support For Laravel 8

### ISSUE THREAD

**Issue by vicky-project** [imanghafoori1/laravel-password-history#19] opened 2021-11-22 17:30 UTC
this packages do not support yet for laravel 8.
it was give me an error while installing Class 'App\User' not found. where it is in default config of this packages.
please update for default config file. thanks

**Comment by sanduluca** [comment] 2022-02-11 09:47
will this be taken in consideration @imanghafoori1 ?

**Comment by imanghafoori1** [comment] 2022-02-11 13:26
yeah
but you have to publish your config file and change it according to your project.
You are not bound to the defaults.

**Comment by sanduluca** [comment] 2022-02-11 14:09
The problem is that I have the following scrips as post-autoload-dump and it fails every time when I try to install the package. Plus the dependencies are installed every time I deploy a new version
```json
"post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
```

So I think it would be better to leave models array empty so that every developer cant add their model.
For example in my case User model is not under the default namespace
```php
'models' => [
        \App\Models\Management\User::class => [
            'password_column' => 'password',
            'guard' => 'web',
        ],
    ],
```

**Comment by imanghafoori1** [comment] 2022-02-11 15:43
I start to think and experiment with it, thank you for the report.

**Comment by imanghafoori1** [comment] 2022-02-11 17:00
@sanduluca could you please test the latest version???
I just commented out all the configs.

**Comment by sanduluca** [comment] 2022-02-11 17:07
Yes. Everything is working fine now.
```bash
$ composer require imanghafoori/laravel-password-history dev-master
./composer.json has been updated
Running composer update imanghafoori/laravel-password-history
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking imanghafoori/laravel-nullable (v1.2.6)
  - Locking imanghafoori/laravel-password-history (dev-master 95d102d)
  - Locking imanghafoori/laravel-smart-facades (v1.0.8)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Downloading imanghafoori/laravel-password-history (dev-master 95d102d)
  - Installing imanghafoori/laravel-smart-facades (v1.0.8): Extracting archive
  - Installing imanghafoori/laravel-nullable (v1.2.6): Extracting archive
  - Installing imanghafoori/laravel-password-history (dev-master 95d102d): Extracting archive
16 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
...
Discovered Package: imanghafoori/laravel-password-history
...
Package manifest generated successfully.
88 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by imanghafoori1** [comment] 2022-02-11 17:17
Closing. Good luck everyone.

**Closed as completed by imanghafoori1** 2022-02-11 17:17 UTC
